# Generated by Django 4.2 on 2023-04-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_recipe_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_ingredients',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
